version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: iot-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: iotProject

    ports:
      - "3366:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: ./backend
    container_name: iot-app

    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/iotProject?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
      SERVER_PORT: 8080

  frontendapp:
    build: ./my-angylar-app
    container_name: my-angular-app
    ports:
      - 4200:4200


volumes:
  mysql_data:
