apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/iotProject?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root123
  SERVER_PORT: "8080"
  SENSOR_API_BASE_URL: http://iot-backend:8080
  SENSOR_SCHEDULER_CRON: "0 */1 * * * *"