apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-backend
  template:
    metadata:
      labels:
        app: iot-backend
    spec:
      containers:
        - name: iot-backend
          image: ahmedyasser02/iotproject:v5.2
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
