apiVersion: v1
kind: Service
metadata:
  name: angular-frontend
spec:
  selector:
    app: angular-frontend
  ports:
    - port: 4200        # external port on the node
      targetPort: 4200  # matches containerPort in deployment
  type: NodePort
