version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: iot-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: dbkms
    ports:
      - "3366:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
